# version: "3"
# services:
#   nginx:
#     build:
#       context: .
#       dockerfile: nginx/Dockerfile
#     ports:
#       - "8080:80"
#     networks:
#       - internal
#     volumes:
#       - ./application/:/var/www/html/
#       - ./logs/nginx:/var/log/nginx/
#     container_name: nginx
#   php:
#     build:
#       context: .
#       dockerfile: php/Dockerfile
#     networks:
#       - internal
#     volumes:
#       - ./application/:/var/www/html/
#       - ./logs/php.log:/var/log/fpm-php.www.log
#     container_name: php
#     expose:
#       - "9000"
#   mysql:
#     container_name: db
#     restart: always
#     image: mysql:latest
#     # platform: linux/x86_64
#     ports:
#      - "3306:3306"
#     environment:
#       MYSQL_USER: 'sushant'
#       MYSQL_PASS: ''
#     volumes:
#       - ./db-data:/var/lib/mysql
#     networks:
#       - internal
# networks:
#   internal:
#     driver: bridge
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: loja-api
    container_name: loja-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"

  mysql:
    image: mysql:latest
    container_name: loja-api_mysql
    # restart: always
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
