version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: loja-api
    container_name: loja-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"

  mysql:
    image: mysql:latest
    container_name: loja-api_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
